server:
  port: 8888

spring:
  application:
    name: configserver
  cloud:
    config:
      name: dinamic-config
      enabled: true
      server:
        git:
          default-label: dinamic-config
          uri: D:\demos\ecommerce-ms-config-server #asdfasdf