server:
  port: 8888

spring:
  application:
    name: configserver
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: D:\demos\ecommerce-ms-config-server #file:///D:/demos/ecommerce-ms-config-server